apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
      - name: wil-app-container
        image: wil42/playground:v2
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-app
  ports:
  - protocol: TCP
    nodePort: 30100
    port: 80
    targetPort: 8888
